# Generated by Django 5.1.7 on 2025-03-22 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_assigned_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 22, 17, 36, 55, 965510, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
