# Generated by Django 5.1.7 on 2025-03-22 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_total_amount_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 22, 17, 35, 41, 622941, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
