# Generated by Django 5.1.7 on 2025-03-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_created_at'),
        ('invoices', '0004_invoice_project_invoice_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
    ]
