# Generated by Django 5.1.7 on 2025-03-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoiceitem_description_alter_invoiceitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='manual_client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
