# Generated by Django 5.1.7 on 2025-03-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='manual_client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
