# Generated by Django 5.1.7 on 2025-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_manual_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='manual_item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
