# Generated by Django 5.1.7 on 2025-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='industry',
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
