# Generated by Django 5.1.7 on 2025-03-22 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_industry_client_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 22, 17, 34, 59, 612873, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
