# Generated by Django 5.1.7 on 2025-03-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
