# Generated by Django 5.1.7 on 2025-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_is_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
