# Generated by Django 5.1.7 on 2025-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_rename_sale_time_sale_sale_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='price_at_sale',
            new_name='price_at_time',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='manual_item_name',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer')], default='cash', max_length=20),
        ),
    ]
