# Generated by Django 5.1.7 on 2025-04-19 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_rename_price_at_sale_saleitem_price_at_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
