# Generated by Django 5.1.7 on 2025-04-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_sale_payment_method_inventorytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='related_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions_pos', to='pos.sale'),
        ),
    ]
